Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -18,9 +18,24 @@ jobs:
       - name: Install dependencies
         run: npm install --ignore-scripts
       - name: Run Snyk to check for vulnerabilities
+        id: snyk-check
         uses: snyk/actions/node@master
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        continue-on-error: true # To make sure that SARIF upload gets called
+        with:
+          args: --severity-threshold=high --sarif-file-output=snyk.sarif
+      - name: Upload result to GitHub Code Scanning
+        id: upload-sarif
+        uses: github/codeql-action/upload-sarif@v3
+        if: steps.snyk-check.outcome == 'failure' && steps.snyk-check.conclusion == 'success'
+        with:
+          sarif_file: snyk.sarif
+      - name: Fail pipeline
+        if: steps.snyk-check.outcome == 'failure' && steps.snyk-check.conclusion == 'success' && steps.upload-sarif.outcome == 'success'
+        run: |
+          echo "::error::Snyk found issues! Go to GitHub Code Scanning to view the issues."
+          exit 1
        
   deploy:
     needs: [build, security]
